name: Build docs

on:
  push:
    branches:
      - '*'
      - 'feature/*'
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  pages: write

# env:
#   DEBUG: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
      
      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22

      - name: Install npm dependencies
        working-directory: ./docs
        run: npm ci
      
      - name: Build project
        working-directory: ./docs
        run: npm run build

      - name: Upload static files as artifact
        id: deployment-pages
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: docs/out/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Deploy to GitHub Pages
        id: deployment-pages
        uses: actions/deploy-pages@v4

      - name: Info
        run: echo "Deployed to ${{ steps.deployment-pages.outputs.page_url }}"